# Build
FROM maven:3-openjdk-17 AS builder
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn package -DskipTests

# Use an openjdk 17 base image as the builder stage
FROM openjdk:17
WORKDIR /app
COPY --from=builder /app/target/OrshaDiary.jar .
CMD ["java", "-jar", "OrshaDiary.jar"]
